### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by georgepoulos** [metalogico/django-sonar#2]
Hello 
I try you software! Its very good.
But you need to find a way to add some permissions on sonar view!

**Comment by metalogico** [comment]
Hi there! Thanks for the message.

Sonar should have a login page that appears if the user is not logged.
Only superusers should be able to access sonar dashboard.

If this is not working I suspect there's a bug! I'm going to check it asap

**Comment by metalogico** [comment]
I've just released 0.1.2 that should fix the problem.
Now only superusers can access Sonar dashboard.
Please let me know if this is ok. Thanks @georgepoulos

**Comment by georgepoulos** [comment]
It looks to work fine!
Thank you!
I will test your project it looks great!
