### ISSUE TITLE
AttributeError: '<custom_user_model>' object has no attribute 'username'

### ISSUE THREAD

**Issue by FraCata00** [metalogico/django-sonar#5]
Note, if has project with custom user model, maybe cannot use the `username` field like the `django.contrib.auth` User model
So, use the `get_user_model` from -> `from django.contrib.auth import get_user_model` and check the model attribute

If you want, i would contribute this project 💯 
I appreciate your work

The error is at user scope in `middleware.request.py`:
![image](https://github.com/metalogico/django-sonar/assets/78490028/76c90d86-1ac4-4260-b127-1643c24e19eb)

**Comment by metalogico** [comment]
Hi, thanks for the heads up!

Probably this solves the problem:

```python
  if request.user.is_authenticated:
        user_info = {
            'user_id': request.user.id,
            'username': request.user.get_username(),
            'email': getattr(request.user, 'email', 'No email provided'),
        }
```

get_username() should safely return the correct field.

**Comment by FraCata00** [comment]
> Hi, thanks for the heads up!
> 
> Probably this solves the problem:
> 
> ```python
>   if request.user.is_authenticated:
>         user_info = {
>             'user_id': request.user.id,
>             'username': request.user.get_username(),
>             'email': getattr(request.user, 'email', 'No email provided'),
>         }
> ```
> 
> get_username() should safely return the correct field.

It's correct!!
Maybe the email field is the username field (in my case)

I think the correct code is:

```python
from django.contrib.auth import get_user_model

User = get_user_model()

# ...... other code
if request.user.is_authenticated:
      user_info = {
                "user_id": request.user.id,
                "username": request.user.get_username(),
                "email": getattr(
                      request.user, User.get_email_field_name(), 'No email provided'
                ),
            }
```

**Comment by metalogico** [comment]
Since the `request.user` is already an instance of the User model (custom or standard), looks like the correct way is:

```python
        if request.user.is_authenticated:
            user_info = {
                'user_id': request.user.id,
                'username': request.user.get_username(),
                'email': getattr(request.user, request.user.get_email_field_name(), 'No email provided'),
            }
```

**Comment by FraCata00** [comment]
> Since the `request.user` is already an instance of the User model (custom or standard), looks like the correct way is:
> 
> ```python
>         if request.user.is_authenticated:
>             user_info = {
>                 'user_id': request.user.id,
>                 'username': request.user.get_username(),
>                 'email': getattr(request.user, request.user.get_email_field_name(), 'No email provided'),
>             }
> ```

It's better to use correct <user> class instead `request.user` for this specific attribute, it's a classmethod, not a standard method

**Comment by metalogico** [comment]
Yes, I see, it makes sense. Thanks for the suggestion.
Would you please move the get_user_model() inside the class, right before the IF checking for authenticated user ?
I prefer having scoped variables instead of globals in the middleware.

**Comment by FraCata00** [comment]
> Yes, I see, it makes sense. Thanks for the suggestion. Would you please move the get_user_model() inside the class, right before the IF checking for authenticated user ? I prefer having scoped variables instead of globals in the middleware.

Sure 👍🏻
